services:
  db1:
    image: postgres:alpine
    container_name: postgres_db1
    environment:
      POSTGRES_USER: usuario1
      POSTGRES_PASSWORD: senha1
      POSTGRES_DB: banco1
    ports:
      - "5432:5432"

  db2:
    image: couchbase:community
    container_name: couchbase_db2
    ports:
      - "8091:8091"   # Portal de administração e API REST
      - "8092:8092"   # Serviço de consulta (query)
      - "11210:11210" # Protocolo memcached para operações de dados